name: Build and Deploy Jupyter Book

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt
          python -m pip list | grep jupyter

      - name: Debug jupyter-book installation
        run: |
          which jupyter-book || echo "jupyter-book not in PATH"
          python -m pip show jupyter-book || echo "jupyter-book not installed"
          python -m pip list | grep jupyter || echo "no jupyter packages"

      - name: Build Jupyter Book
        run: |
          jupyter-book build psd/

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          ghp-import -n -p -f psd/_build/html -b gh-pages
